/* generated by tools/build.py - do not edit */
var CACHE='proactivity-21cb9f2b7383';
var SHELL=['./','./index.html','./icon-192.png','./icon-512.png','./manifest.webmanifest'];
self.addEventListener('install', function(e){
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then(function(c){ return c.addAll(SHELL).catch(function(){}); }));
});
self.addEventListener('activate', function(e){
  e.waitUntil(caches.keys().then(function(ks){
    return Promise.all(ks.map(function(k){ return k===CACHE ? null : caches.delete(k); }));
  }).then(function(){ return self.clients.claim(); }));
});
self.addEventListener('fetch', function(e){
  var req=e.request;
  if(req.method!=='GET') return;
  var url=new URL(req.url);
  if(url.origin!==location.origin) return;        /* fonts and the licence API go straight out */
  var isDoc = req.mode==='navigate' || (req.headers.get('accept')||'').indexOf('text/html')>=0;
  if(isDoc){
    e.respondWith(fetch(req).then(function(r){
      var copy=r.clone();
      caches.open(CACHE).then(function(c){ c.put('./index.html', copy); });
      return r;
    }).catch(function(){ return caches.match('./index.html'); }));
    return;
  }
  e.respondWith(caches.match(req).then(function(hit){
    return hit || fetch(req).then(function(r){
      if(r && r.status===200){ var copy=r.clone(); caches.open(CACHE).then(function(c){ c.put(req,copy); }); }
      return r;
    });
  }));
});
